"""Adding picks table

Revision ID: 0db9576da356
Revises: 43085cb84d54
Create Date: 2019-05-23 02:29:18.995590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db9576da356'
down_revision = '43085cb84d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=140), nullable=True),
    sa.Column('album', sa.String(length=140), nullable=True),
    sa.Column('song', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_timestamp'), 'pick', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_timestamp'), table_name='pick')
    op.drop_table('pick')
    # ### end Alembic commands ###
