"""test

Revision ID: 43085cb84d54
Revises: 
Create Date: 2019-05-23 02:22:32.929285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43085cb84d54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
